build release:
  stage: build
  image: registry.gitlab.com/promethist/system/builder
  only:
    - tags
  script:
    - mvn versions:set -DnewVersion=$CI_COMMIT_REF_NAME
    - mvn -B deploy

build snapshot:
  stage: build
  image: registry.gitlab.com/promethist/system/builder
  only:
    - develop
  script:
    - mvn -B deploy
